### ISSUE TITLE
'infos_xe-best.pkl': No such file or directory

### ISSUE THREAD

**Issue by arjung128** [lukemelas/image-paragraph-captioning#2]
When I trained the network, it didn't create a "infos_xe-best.pkl" file so I get an error when I run "./scripts/copy_model.sh xe sc". Any ideas on what I might be missing?

**Comment by lukemelas** [comment]
That's odd. Have you been able to resolve this issue or are you still having trouble? Also, did you name your original run _xe_ (that's what was intended), or something different?

**Comment by arjung128** [comment]
I'm still having this issue. I followed the instructions on the readme.md and I'm not sure why this file wasn't created when the training cutoff after the 29th epoch...

**Comment by lukemelas** [comment]
Strange, what is the output of `ls log_xe`?

**Comment by arjung128** [comment]
histories_xe.pkl                   model-best-i06000-score0.0439.pth  model-best-i15000-score0.0562.pth  model-best-i24000-infos.pkl        model-best-i36000-infos.pkl
infos_xe.pkl                       model-best-i09000-infos.pkl        model-best-i15000-score0.0690.pth  model-best-i24000-score0.0992.pth  model-best-i36000-score0.1107.pth
model-best-i03000-infos.pkl        model-best-i09000-score0.0449.pth  model-best-i18000-infos.pkl        model-best-i30000-infos.pkl        model-best-i42000-infos.pkl
model-best-i03000-score0.0147.pth  model-best-i09000-score0.0455.pth  model-best-i18000-score0.0590.pth  model-best-i30000-score0.0842.pth  model-best-i42000-score0.1048.pth
model-best-i03000-score0.0313.pth  model-best-i12000-infos.pkl        model-best-i21000-infos.pkl        model-best-i33000-infos.pkl        model.pth
model-best-i06000-infos.pkl        model-best-i12000-score0.0473.pth  model-best-i21000-score0.0816.pth  model-best-i33000-score0.0983.pth  optimizer.pth
model-best-i06000-score0.0411.pth  model-best-i15000-infos.pkl        model-best-i21000-score0.0957.pth  model-best-i33000-score0.1018.pth

**Comment by lukemelas** [comment]
Ah, I see. Rename your latest model (or your best model, according to the validation score, whichever). For example, something like: 
```
cd log_xe
cp model-best-i33000-infos.pkl infos_xe-best.pkl
```

**Comment by arjung128** [comment]
This workaround worked. Thanks!

But this shouldn't need a workaround, should it?

**Comment by lukemelas** [comment]
Great! Yup, I can edit stuff to make it work without copying the file.
