### ISSUE TITLE
Return value of get_batch()

### ISSUE THREAD

**Issue by arjung128** [lukemelas/image-paragraph-captioning#5]
Line 115 of train.py is: 

data = loader.get_batch('train’)

Where data is a dictionary with 8 keys: ['labels', 'bounds', 'masks', 'gts', 'att_masks', 'infos', 'att_feats', 'fc_feats’]

My understanding is the following:

Labels: the caption, where each word is represented by a number from the ordered vocabulary (why does this always start with 0?)
Bounds: {'wrapped': False, 'it_pos_now': 10, 'it_max': 14574} — not entirely sure what these mean
Masks: the i’th index is 1 whenever the i’th word exists
Gts: the labels array shifted over to the left by 1, getting rid of the starting 0 in labels
att_masks: not sure
Infos: information about the images in the batch

Is my limited understanding correct? I have no idea what att_feats and fc_feats are…what are they? Is the encoder output stored anywhere in this ‘data' dictionary?

**Comment by lukemelas** [comment]
Yes, you are correct. The starting 0 is the beginning-of-sentence token. `att_feats` is the attention feature vector and `fc_feats` are the pooled attention feature vectors (the output of the fully connected layer of the CNN). For more information, see Ruotian Luo's repo: https://github.com/ruotianluo/self-critical.pytorch
