### ISSUE TITLE
Problem with Pre-trained model  

### ISSUE THREAD

**Issue by sabirdvd** [lukemelas/image-paragraph-captioning#7]
Hey luke, Thank you very much for sharing your work.

I'm trying to do some experiment with the uploaded pretrained model, to do some inference, But the pre-trained model is just generating a UNK word. 

I used this flags 
`python eval.py --model data/model-best-i84000-score0.314696218186.pth --infos_path data/for_zip/infos_-best.pkl --image_folder data/image`

![unk](https://user-images.githubusercontent.com/18333226/60432552-dd68a080-9c02-11e9-810d-efc2568a8df3.png)

Also, the eval_utils.py have the same problem with (https://github.com/ruotianluo/self-critical.pytorch/issues/42 with KeyError: 'att_masks' )
I found a solution from this link, would be great to update the file with this modified code
https://github.com/ruotianluo/self-critical.pytorch/issues/42

`tmp = [data['fc_feats'][np.arange(loader.batch_size) * loader.seq_per_img], 
	    data['att_feats'][np.arange(loader.batch_size) * loader.seq_per_img], 
            data['att_masks'][np.arange(loader.batch_size) * loader.seq_per_img] if 'att_masks' in data is not None else None]      `

Again, Thank you for sharing your work

**Comment by pidugusundeep** [comment]
@sabirdvd Even i get 'UNK' like the same as you have, is that problem with the trained model ??

**Comment by cczka** [comment]
got the same problem, is there any solution?
